### PR TITLE
Support for Multi Browser Windows

### PR DESCRIPTION
**Pull request by meligaletiko**
* Added browserWindow to the object tab
* Added logic to detect if tab browser window still exists. Open otherwise
* Changed for loop with every
* Removed commas

### CODE REVIEW

**Comment by bucaran** [comment]
Thanks @meligaletiko. The new PR should go into a new branch (of the same new `multi-browser-window`). In other words, we are not merging the changes into master, but the new branch.

**Comment by meligaletiko** [comment]
If you don't want this feature, you can always deny the MR, it's fine by me, i'm using my version. I think is a great feature that improve a lot the extension.

I'm already working on the new feature, the one that stores the tabs in the browser local storage, so when the user restores the session he gets the closed tabs.
I'm doing that as an option, so the user can enable and disable it from the extension settings.

But as i said, let me know if you don't want the feature, it's ok by me.

Oh, in the gallery extension version, when i restore the session, the extension doesn't works, because the update of the tab index. The javascript crashes and then i'm not able to use it.
It doesn't happens with this version.

**Comment by meligaletiko** [comment]
@bucaran i'm closing the PR ;)

**Comment by bucaran** [comment]
@meligaletiko Thanks again! If you make a PR to a new branch I will definitely merge into that branch and compile a bundle and create a release. Eventually it would be like maintaining two different versions.

**Comment by meligaletiko** [comment]
@bucaran ok, but you need to create the branch on your side. But you can always merge it to the master and create a tag.
But well, create the branch and tell me which is so i can perform the PR ;)

Thanks :)

**Comment by bucaran** [comment]
```
`multi-window` created.
> 0 s
```
Done.

**Pull request closed without merging**
