### PR TITLE
Support for multiple browser windows

### PR DESCRIPTION
**Pull request by meligaletiko**
* Added browserWindow to the object tab
* Added logic to detect if tab browser window still exists. Open otherwise

I pretend to perform a few more changes, to support save and restore when user restores a session.

### CODE REVIEW

**Comment by bucaran** [comment]
Hey @meligaletiko, adding support for this is definitely the way to go, but I am not so positive about the code. I think this could be implemented in just a few extra lines.

Also, sorry for not specifying this anywhere, but 

1. `for (var i = 0; i < ; i++) {` like for loops :-1: 
2. Declaring variables: :-1: 

Also, doesn't this `(!browserWindow)` work too?

**Comment by meligaletiko** [comment]
Hi @bucaran.

I've be using this code without problems so far. About the code, i'm a C++, objC developer, i'm no so used to javascript. The last time i do something big in Javascript was with Node and it has been at almost two years ago.

About your comments:
1. `for (var i = 0; i < ; i++)` as far as i know, `forEach` to iterate doesn't supports break, as we are in a different context, since we're in a callback
2. I think i know what i'm doing, and this vars are needed. one to the browser window and another to the tab, so i don't need to repeat some unnecessary code or create a function to avoid context change.
3. About the semicolons, as i told you a full-time C++ and objC developer, so i'm used to use it.

Yes, the `!!` are really not necessary. In time i have a problem so i need to use `!!` to force a `false` value, but not `!!!` sorry.

So about the old way loop, i also prefer to use `forEach`, do you have any suggestion? `for .. in`?

Thanks

**Comment by meligaletiko** [comment]
Oh ok, i remember now the problem with `for (var i = 0; i < ; i++)`. I was seeing my old stuff and i notice that i perform array loops in a reverse order.

The only problem i see, is that usually the tab that i'm looking for is at the index 0, but performing the loop through the reverse the order will only found the window in the last iteration.

**Comment by bucaran** [comment]
Let's do something, simply create a new branch, something like `multi-browser-window` and send me a new PR.

**Comment by bucaran** [comment]
> forEach to iterate doesn't supports break, as we are in a different context, since we're in a callback

That's correct. In this case we use `every` or [`some`](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Array/some) depending on what you want to achieve.

**Comment by meligaletiko** [comment]
Holly hell, it looks that i'm been hacked or something, i'm doing some mistakes :disappointed: 

1. About the branch, u'r totally right, i used to do that, i rarely use master for commits, sorry
2. About the for loop, i was using `every` but i misunderstood the doc so i was returning true when i found the element. :disappointed: :-1: ups

On my way to fix it...

Thanks

**Comment by bucaran** [comment]
@meligaletiko 

1. I meant, the PR should go into a _new_ branch on my repo, so that we don't have to merge into master.

2. Tell me about it :laughing:

**Pull request closed without merging**
